WHENEVER SQLERROR CONTINUE NONE

-- ユーザ削除（存在しない場合、エラーとなるが無視する）
DROP USER USER1 CASCADE
/

WHENEVER SQLERROR EXIT SQL.SQLCODE

-- USER1の登録
CREATE USER USER1
IDENTIFIED BY ********
DEFAULT TABLESPACE SYSTEM
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT
/
GRANT DBA TO USER1
/
GRANT UNLIMITED TABLESPACE TO USER1
/

EXIT 0
