-- table_def.csv çÏê¨óp

WITH
PK_LIST AS (
  SELECT
    CC.TABLE_NAME, CC.COLUMN_NAME, CC.POSITION AS PK_ID
  FROM
    USER_CONS_COLUMNS CC, USER_CONSTRAINTS C
  WHERE
    (CC.CONSTRAINT_NAME = C.CONSTRAINT_NAME) AND (C.CONSTRAINT_TYPE = 'P')
  ORDER BY
    CC.TABLE_NAME, CC.POSITION
)

SELECT
  TC.TABLE_NAME
  , TC.COLUMN_NAME
  , TC.COLUMN_ID
  , TC.DATA_TYPE
  , PK.PK_ID
FROM
  USER_TAB_COLUMNS TC

  INNER JOIN USER_TABLES T
    ON (TC.TABLE_NAME = T.TABLE_NAME)

  LEFT JOIN PK_LIST PK
    ON (TC.TABLE_NAME = PK.TABLE_NAME)
    AND (TC.COLUMN_NAME = PK.COLUMN_NAME)

ORDER BY
  TC.TABLE_NAME
  , TC.COLUMN_ID
