SET NOCOUNT ON
DECLARE @SQL As NVARCHAR(2000)

-- BULK INSERT
SET @SQL = N'BULK INSERT $(TABLE_NAME) FROM ''$(CURRENT_DIR)tsv\$(TABLE_NAME)$(EXTENSION)''
WITH(CHECK_CONSTRAINTS, KEEPIDENTITY, FIRSTROW=1, FIELDTERMINATOR=''$(FIELDTERMINATOR)'', ROWTERMINATOR=''\n'', FORMATFILE=''$(CURRENT_DIR)$(FORMAT)'')'

Print 'BULK INSERT STARTÅF$(TABLE_NAME)'
EXEC spexecutesql @SQL

DEClARE @CNT As Int
SELECT @CNT = COUNT(*) FROM $(TABLE_NAME)
Print CAST(@CNT As Varchar) + "åèèàóùÇµÇ‹ÇµÇΩÅB"

Print 'BULK INSERT END  : $(TABLE_NAME)'
