-- 以下のSQLを実行し「main」シートに貼り付ける

SELECT
  TABLE_NAME
FROM
  USER_TABLES
ORDER BY
  TABLE_NAME



-- 以下のSQLを実行し「work」シートに貼り付ける

WITH
R_LIST AS (

  SELECT DISTINCT
    C.TABLE_NAME,
    CC.TABLE_NAME AS FK_TABLE_NAME
  FROM
    USER_CONSTRAINTS C, 
    USER_CONS_COLUMNS CC
  WHERE
    (CONSTRAINT_TYPE = 'R') AND 
    (C.R_CONSTRAINT_NAME = CC.CONSTRAINT_NAME)
  ORDER BY
    C.TABLE_NAME
)

SELECT DISTINCT
  R1.TABLE_NAME, 
  R1.FK_TABLE_NAME,
  R2.FK_TABLE_NAME,
  R3.FK_TABLE_NAME,
  R4.FK_TABLE_NAME, 
  R5.FK_TABLE_NAME, 
  R6.FK_TABLE_NAME
FROM
  R_LIST R1
LEFT JOIN R_LIST R2 ON (R1.FK_TABLE_NAME = R2.TABLE_NAME)
LEFT JOIN R_LIST R2 ON (R2.FK_TABLE_NAME = R3.TABLE_NAME)
LEFT JOIN R_LIST R2 ON (R3.FK_TABLE_NAME = R4.TABLE_NAME)
LEFT JOIN R_LIST R2 ON (R4.FK_TABLE_NAME = R5.TABLE_NAME)
LEFT JOIN R_LIST R2 ON (R5.FK_TABLE_NAME = R6.TABLE_NAME)
ORDER BY
  1, 2, 3, 4, 5, 6, 7
