-- 以下のSQLを実行し「main」シートに貼り付ける

select TABLE_NAME from USER_TABLES order by TABLE_NAME



-- 以下のSQLを実行し「work」シートに貼り付ける

WITH
R_LIST AS (
  select distinct C.TABLE_NAME, CC.TABLE_NAME AS FK_TABLE_NAME from USER_CONSTRAINTS C, USER_CONS_COLUMNS CC
  where (CONSTRAINT_TYPE = 'R') AND (C.R_CONSTRAINT_NAME = CC.CONSTRAINT_NAME) order by C.TABLE_NAME
)
select distinct
  R1.TABLE_NAME, R1.FK_TABLE_NAME, R2.FK_TABLE_NAME, R3.FK_TABLE_NAME, R4.FK_TABLE_NAME, R5.FK_TABLE_NAME, R6.FK_TABLE_NAME
from
  R_LIST R1
left join R_LIST R2 on (R1.FK_TABLE_NAME = R2.TABLE_NAME)
left join R_LIST R2 on (R2.FK_TABLE_NAME = R3.TABLE_NAME)
left join R_LIST R2 on (R3.FK_TABLE_NAME = R4.TABLE_NAME)
left join R_LIST R2 on (R4.FK_TABLE_NAME = R5.TABLE_NAME)
left join R_LIST R2 on (R5.FK_TABLE_NAME = R6.TABLE_NAME)
order by 1, 2, 3, 4, 5, 6, 7
